/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Album {
  'id' : bigint,
  'contents' : Array<AlbumContentEntry>,
  'name' : string,
}
export interface AlbumContentEntry {
  'contentId' : bigint,
  'position' : bigint,
  'isVideo' : boolean,
}
export interface AlbumEntryInput {
  'contentId' : bigint,
  'position' : bigint,
  'isVideo' : boolean,
}
export type AlbumId = bigint;
export interface AlbumInput { 'name' : string }
export type DeleteAlbumResponse = { 'permissionDenied' : string } |
  { 'error' : string } |
  { 'success' : string };
export type ExternalBlob = Uint8Array;
export interface Photo {
  'id' : bigint,
  'filename' : string,
  'storageRef' : ExternalBlob,
  'customOrder' : bigint,
  'uploadDate' : Time,
}
export type PhotoId = bigint;
export interface PhotoUploadInput {
  'content' : ExternalBlob,
  'filename' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : bigint,
  'mimeType' : string,
  'filename' : string,
  'storageRef' : ExternalBlob,
  'customOrder' : bigint,
  'uploadDate' : Time,
}
export interface VideoUploadInput {
  'content' : ExternalBlob,
  'filename' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEntryToAlbum' : ActorMethod<[AlbumId, AlbumEntryInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlbum' : ActorMethod<[AlbumInput], AlbumId>,
  'deleteAlbum' : ActorMethod<[bigint], DeleteAlbumResponse>,
  'deletePhoto' : ActorMethod<[bigint], undefined>,
  'deleteVideo' : ActorMethod<[bigint], undefined>,
  'getAllAlbums' : ActorMethod<[], Array<Album>>,
  'getAllPhotos' : ActorMethod<[], Array<Photo>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'movePhotoToAlbum' : ActorMethod<[PhotoId, AlbumId], undefined>,
  'rearrangePhotos' : ActorMethod<[Array<bigint>], undefined>,
  'rearrangeVideos' : ActorMethod<[Array<bigint>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadPhoto' : ActorMethod<[PhotoUploadInput], undefined>,
  'uploadVideo' : ActorMethod<[VideoUploadInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];