/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AlbumId = IDL.Nat;
export const AlbumEntryInput = IDL.Record({
  'contentId' : IDL.Nat,
  'position' : IDL.Nat,
  'isVideo' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlbumInput = IDL.Record({ 'name' : IDL.Text });
export const DeleteAlbumResponse = IDL.Variant({
  'permissionDenied' : IDL.Text,
  'error' : IDL.Text,
  'success' : IDL.Text,
});
export const AlbumContentEntry = IDL.Record({
  'contentId' : IDL.Nat,
  'position' : IDL.Nat,
  'isVideo' : IDL.Bool,
});
export const Album = IDL.Record({
  'id' : IDL.Nat,
  'contents' : IDL.Vec(AlbumContentEntry),
  'name' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Photo = IDL.Record({
  'id' : IDL.Nat,
  'filename' : IDL.Text,
  'storageRef' : ExternalBlob,
  'customOrder' : IDL.Nat,
  'uploadDate' : Time,
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'storageRef' : ExternalBlob,
  'customOrder' : IDL.Nat,
  'uploadDate' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PhotoId = IDL.Nat;
export const PhotoUploadInput = IDL.Record({
  'content' : ExternalBlob,
  'filename' : IDL.Text,
});
export const VideoUploadInput = IDL.Record({
  'content' : ExternalBlob,
  'filename' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEntryToAlbum' : IDL.Func([AlbumId, AlbumEntryInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlbum' : IDL.Func([AlbumInput], [AlbumId], []),
  'deleteAlbum' : IDL.Func([IDL.Nat], [DeleteAlbumResponse], []),
  'deletePhoto' : IDL.Func([IDL.Nat], [], []),
  'deleteVideo' : IDL.Func([IDL.Nat], [], []),
  'getAllAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
  'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'movePhotoToAlbum' : IDL.Func([PhotoId, AlbumId], [], []),
  'rearrangePhotos' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'rearrangeVideos' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadPhoto' : IDL.Func([PhotoUploadInput], [], []),
  'uploadVideo' : IDL.Func([VideoUploadInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AlbumId = IDL.Nat;
  const AlbumEntryInput = IDL.Record({
    'contentId' : IDL.Nat,
    'position' : IDL.Nat,
    'isVideo' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlbumInput = IDL.Record({ 'name' : IDL.Text });
  const DeleteAlbumResponse = IDL.Variant({
    'permissionDenied' : IDL.Text,
    'error' : IDL.Text,
    'success' : IDL.Text,
  });
  const AlbumContentEntry = IDL.Record({
    'contentId' : IDL.Nat,
    'position' : IDL.Nat,
    'isVideo' : IDL.Bool,
  });
  const Album = IDL.Record({
    'id' : IDL.Nat,
    'contents' : IDL.Vec(AlbumContentEntry),
    'name' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Photo = IDL.Record({
    'id' : IDL.Nat,
    'filename' : IDL.Text,
    'storageRef' : ExternalBlob,
    'customOrder' : IDL.Nat,
    'uploadDate' : Time,
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'storageRef' : ExternalBlob,
    'customOrder' : IDL.Nat,
    'uploadDate' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PhotoId = IDL.Nat;
  const PhotoUploadInput = IDL.Record({
    'content' : ExternalBlob,
    'filename' : IDL.Text,
  });
  const VideoUploadInput = IDL.Record({
    'content' : ExternalBlob,
    'filename' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEntryToAlbum' : IDL.Func([AlbumId, AlbumEntryInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlbum' : IDL.Func([AlbumInput], [AlbumId], []),
    'deleteAlbum' : IDL.Func([IDL.Nat], [DeleteAlbumResponse], []),
    'deletePhoto' : IDL.Func([IDL.Nat], [], []),
    'deleteVideo' : IDL.Func([IDL.Nat], [], []),
    'getAllAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
    'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'movePhotoToAlbum' : IDL.Func([PhotoId, AlbumId], [], []),
    'rearrangePhotos' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'rearrangeVideos' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadPhoto' : IDL.Func([PhotoUploadInput], [], []),
    'uploadVideo' : IDL.Func([VideoUploadInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };